### ISSUE TITLE
FYI: Arduino Nano ESP32 Doensn't like excisting commands like pinMode

### ISSUE THREAD

**Issue by wltue** [RobTillaart/MCP23008#13]
Arduino Nano ESP32. Including your library puts out:
In file included from C:\Users\----\AppData\Local\Arduino15\packages\arduino\hardware\esp32\2.0.13\cores\esp32/Arduino.h:223,
                 from C:\Users\---\MCP23008\Arduino\MCP23008_test\MCP23008.h:10,
                 from C:\Users\---\MCP23008\Arduino\MCP23008_test\MCP23008.cpp:9:
C:\Users\---\AppData\Local\Arduino15\packages\arduino\hardware\esp32\2.0.13\cores\esp32/io_pin_remap.h:47:61: error: 'digitalPinToGPIONumber' is not a type
 #define pinMode(pin, mode)                          pinMode(digitalPinToGPIONumber(pin), mode)
                                                             ^~~~~~~~~~~~~~~~~~~~~~
C:\Users\---\MCP23008\Arduino\MCP23008_test\MCP23008.h:36:8: note: in expansion of macro 'pinMode'
   bool pinMode(uint8_t pin, uint8_t mode);
..... etc.

changing in .h
  bool pinMope(uint8_t pin, uint8_t mode);
  bool digitalWripe(uint8_t pin, uint8_t value);
  uint8_t digitalReat(uint8_t pin);

  //      8 pins interface
  //      value = bit pattern
  bool pinMope8(uint8_t value);
  bool write8(uint8_t value);

  //      DEBUG functions
  uint8_t getpinMope8();

and in .cpp accordingly, works now fine.
I guess the ESP32 doesn't recognize that its in a class.
Just a quick report.
Thank you.

**Comment by RobTillaart** [comment]
This is a known problem with the Arduino Nano ESP32, imho a bug.

By renaming well known function names with **macros** the compiler also renames functions that are members of a class.
The Preprocessor which executes the macros (text replacements) does not know any bit of code context. 
This is both a gift and horror. In this case the latter.

It is NOT an ESP32 problem as other ESP32 based boards do not have this problem.
It is definitely an Arduino NANO software design problem.

**Comment by RobTillaart** [comment]
PS,
I find it strange that you need to replace **pinMode8()** too as that is not in the **io_pin_remap.h** file

I would rename to **pinMode1(), digitalWrite1(), digitalRead1()**, just adding the number of bits used.
That would keep it readable and is informative.

**Comment by wltue** [comment]
Thanks. Just very busy atm. Sorry for mistakes in my report.

**Comment by RobTillaart** [comment]
No need to apologize,
This kind of reports are appreciated as they help to define the scope of the libraries.
For me, I have made an action point to check all my 200+ libraries for this and add a section to the readme.

**Comment by wltue** [comment]
Your a Arduino Legend, thanks for all your work within the years :-)
