### ISSUE TITLE
Error in digitalRead example

### ISSUE THREAD

**Issue by ilguargua** [RobTillaart/MCP23008#7]
Hi there,
there is an error in the MCP23008_digitalRead  example:

MCP.pinMode8(0x00);

should instead be:

MCP.pinMode8(0xFF);

Cheers, Ale.

**Comment by RobTillaart** [comment]
Thanks for reporting, will have a look asap

**Comment by RobTillaart** [comment]
Fixed in master branch, not made a new release.
Again thanks for reporting!
